# SPDX-FileCopyrightText: 2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Habitat-ROS node settings

# Subscribed topics
external_pose_topic_name: "/habitat/external_pose"

# Sensor settings
width: 640
height: 480

# Other settings
scene_file: "habitat_sim/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb"
#scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/1LXtFkjw3qL/1LXtFkjw3qL.glb"
publisher_rate: 30
enable_external_pose: true
enable_semantics: false
visualize_semantics: false

