# SPDX-FileCopyrightText: 2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Habitat-ROS node settings

# Published topics
rgb_topic_name: "/habitat/rgb"
depth_topic_name: "/habitat/depth"
semantic_class_topic_name: "/habitat/semantic_class"
semantic_instance_topic_name: "/habitat/semantic_instance"
habitat_pose_topic_name: "/habitat/pose"

# Subscribed topics
external_pose_topic_name: "/habitat/ext_pose"
external_pose_topic_type: "geometry_msgs::PoseStamped"

# Sensor settings
width: 640
height: 480

# Other settings
scene_file: "habitat_sim/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb"
enable_external_pose: false

