# SPDX-FileCopyrightText: 2020-2021 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020-2021 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Habitat-ROS node settings
habitat:
    # Sensor settings
    width: 640
    height: 480
    near_plane: 0.1
    far_plane: 20.0
    fx: 525.0
    fps: 30
    enable_semantics: false
    allowed_classes: []

    # Scene settings
    scene_file: "habitat_sim/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb"
    #scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/1LXtFkjw3qL/1LXtFkjw3qL.glb"
    initial_T_WB: []
    world_frame_id: "map"

    # Visualization settings
    visualize_semantics: false

